from setuptools import setup

setup(name='astrobulb',
      version='0.0.1',
      description='Photometry Pipeline',
      author='Ben Tofflemire',
      author_email='tofflemire@utexas.edu',
      url='https://github.com/tofflemire/astrobulb',
      license='MIT',
      classifiers=[
          'Development Status :: 3 - Alpha',
          'Intended Audience :: Science/Research',
          'License :: OSI Approved :: MIT License',
          'Programming Language :: Python',
          'Topic :: Scientific/Engineering :: Astronomy',
          ],
      packages=['astrobulb'],
      requires=['numpy',
                'os',
                'time',
                'astropy',
                'scipy',
                'matplotlib',
                'pickle',
                'PyQt5',
                'copy',
                'glob',
                'sys',
                'saphires',
                'astroquery',
                'ccdproc',
                'photutils'])